package io.bkr.hr.entity;

public enum TypesOfDisorders {
    DOESNOTAPPLY,
    PHYSICALDISABILITY,
    BRAINLESIONS,
    VISUALDISTURBANCE,
    HEARINGIMPAIRMENT,
    LANGUAGEDISTURBANCE,
    MENTALWEAKNESS,
    MENTALDISORDER,
    AUTISM,
    RENALDISORDER,
    HEARTDEFECT,
    RESPIRATORYDISORDER,
    HEPATOPATHY,
    TRADIVEDYSKINESIA;

}
